Repository simple-icons/simple-icons-font, pull requests merged in 2020-12, with the labels that each got.

#40 Switch from Travis CI to GitHub Actions
  .github/workflows/publish.yml
  .github/workflows/verify.yml
  .travis.yml
Labels: meta

#39 Logic for CSS class generation to use for icons
  .gitignore
  package.json
  preview/css/base.css
  preview/html/testpage.pug
  scripts/buildCss.js
  scripts/buildFont.js
  scripts/buildTestpage.js
  scripts/utils.js
Labels: enhancement

#43 Add black/colored icons toggler to preview page
  preview/assets/script.js
  preview/assets/style.css
  preview/html/testpage.pug
Labels: enhancement

#44 Less ligatures per icon
  scripts/buildCss.js
  scripts/buildFont.js
  scripts/buildTestpage.js
  scripts/utils.js
Labels: bug, enhancement

#45 Replace fonts build system
  .npmignore
  .svgo.yml
  package-lock.json
  package.json
  preview/css/base.css
  preview/html/testpage.pug
  scripts/build.js
  scripts/buildCss.js
  scripts/buildFont.js
  scripts/buildTestpage.js
  scripts/svgo.js
  scripts/templates/font.svg
Labels: bug, dependencies, enhancement

#47 Customize generated fonts metadata
  scripts/build.js
Labels: enhancement

#48 Generate minified CSS at build process
  package-lock.json
  package.json
  scripts/build.js
Labels: dependencies, enhancement

#50 Release v2
  .gitattributes
  .github/renovate.json5
  .github/workflows/publish.yml
  .github/workflows/verify.yml
  .gitignore
  .npmignore
  .travis.yml
  README.md
  font/font.css
  font/test-assets/script.js
  package-lock.json
  package.json
  preview/assets/script.js
  preview/assets/style.css
  preview/css/base.css
  preview/html/testpage.pug
  scripts/build.js
  scripts/buildTestpage.js
  scripts/templates/font.svg
  src/html/test.pug
Labels: release

#52 Build in publish workflow using 'prepublishOnly' script
  .github/workflows/publish.yml
Labels: meta

#53 Add setup and usage documentation to README
  README.md
Labels: docs

#54 Set up automated GitHub releases
  .github/workflows/publish.yml
  README.md
Labels: meta

#55 Release v2.0.1
  .github/workflows/publish.yml
  .github/workflows/verify.yml
  README.md
  package-lock.json
  package.json
Labels: release

#56 Add Verify workflow job to verify build:testpage
  .github/workflows/verify.yml
  .gitignore
  package-lock.json
  package.json
  scripts/preview.js
Labels: dependencies, meta

#59 Fix color modifier classname in README Usage
  README.md
Labels: docs
