Repository simple-icons/simple-icons-font, pull requests merged in 2021-01, with the labels that each got.

#60 Update simple-icons dependency to v2.19.0
  package-lock.json
  package.json
Labels: dependencies

#61 Release v2.19.0
  .github/workflows/auto-release.yml
  .github/workflows/verify.yml
  .gitignore
  README.md
  package-lock.json
  package.json
  scripts/preview.js
Labels: release

#63 Update simple-icons dependency to v3.13.0
  package-lock.json
  package.json
Labels: breaking change, dependencies

#58 Implement shorter class names
  README.md
  preview/assets/script.js
  preview/assets/style.css
  preview/css/base.css
  preview/html/testpage.pug
  scripts/build.js
Labels: breaking change, enhancement

#64 Release v3.13.0
  .github/workflows/verify.yml
  .gitignore
  README.md
  package-lock.json
  package.json
  preview/assets/script.js
  preview/assets/style.css
  preview/css/base.css
  preview/html/testpage.pug
  scripts/build-testpage.js
  scripts/build.js
Labels: release

#66 Minor repository improvements
  .editorconfig
  .gitattributes
  CONTRIBUTING.md
  README.md
Labels: docs, meta

#69 Release v3.13.1
  .editorconfig
  .gitattributes
  CONTRIBUTING.md
  README.md
  package-lock.json
  package.json
Labels: release

#65 Update simple-icons dependency to v4.0.0
  package-lock.json
  package.json
Labels: breaking change, dependencies

#70 Release v4.0.0
  README.md
  package-lock.json
  package.json
Labels: release

#71 Add issue templates (+ minor change to CONTRIBUTING.md)
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/font.md
  CONTRIBUTING.md
Labels: meta

#72 Update simple-icons dependency to v4.1.0
  package-lock.json
  package.json
Labels: dependencies

#74 Release v4.1.0
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/font.md
  CONTRIBUTING.md
  package-lock.json
  package.json
Labels: release

#73 Set up Prettier code style
  .editorconfig
  .github/ISSUE_TEMPLATE/config.yml
  .github/renovate.json5
  .github/workflows/auto-release.yml
  .github/workflows/publish.yml
  .github/workflows/verify.yml
  .prettierignore
  package-lock.json
  package.json
  preview/assets/script.js
  preview/assets/style.css
  preview/css/base.css
  preview/html/testpage.pug
  scripts/build-testpage.js
  scripts/build.js
  scripts/preview.js
  scripts/version.js
Labels: dependencies, meta

#75 Update simple-icons dependency to v4.2.0
  package-lock.json
  package.json
Labels: dependencies

#76 Release v4.2.0
  .editorconfig
  .github/ISSUE_TEMPLATE/config.yml
  .github/renovate.json5
  .github/workflows/auto-release.yml
  .github/workflows/publish.yml
  .github/workflows/verify.yml
  .prettierignore
  package-lock.json
  package.json
  preview/assets/script.js
  preview/assets/style.css
  preview/css/base.css
  preview/html/testpage.pug
  scripts/build-testpage.js
  scripts/build.js
  scripts/preview.js
  scripts/version.js
Labels: release

#78 Update simple-icons dependency to v4.3.0
  package-lock.json
  package.json
Labels: dependencies

#79 Release v4.3.0
  package-lock.json
  package.json
Labels: release

#80 Update simple-icons dependency to v4.4.0
  package-lock.json
  package.json
Labels: dependencies

#81 Release v4.4.0
  package-lock.json
  package.json
Labels: release

#82 Update simple-icons dependency to v4.5.0
  package-lock.json
  package.json
Labels: dependencies

#83 Release v4.5.0
  package-lock.json
  package.json
Labels: release

#77 Set up automated releases workflow
  .github/workflows/auto-release.yml
  package.json
  scripts/bump-version.js
  scripts/version.js
Labels: dependencies, meta

#85 Setup pre-commit autoformatting with Husky
  .husky/.gitignore
  .husky/pre-commit
  package-lock.json
  package.json
Labels: dependencies, meta

#89 Use 'punycode/' require to import the userland module
  scripts/build.js
Labels: refactor

#86 General refactoring for consistency
  preview/assets/script.js
  scripts/build-testpage.js
  scripts/build.js
  scripts/preview.js
  scripts/templates/base.css
Labels: refactor

#91 Update Renovate configuration
  .github/renovate.json5
Labels: meta

#92 General refactoring for consistency
  scripts/build-testpage.js
  scripts/build.js
  scripts/bump-version.js
  scripts/preview.js
Labels: refactor

#94 Usage of 'pinst' in hooks to prevent postinstall execution during remote installation
  package-lock.json
  package.json
Labels: bug, meta

#95 Release v4.6.1
  .github/renovate.json5
  .gitignore
  .prettierignore
  package-lock.json
  package.json
  scripts/build-testpage.js
  scripts/build.js
  scripts/bump-version.js
  scripts/preview.js
Labels: release

#96 Place badges before 'Usage'
  README.md
Labels: meta
