Repository simple-icons/simple-icons-font, pull requests merged in 2021-02, with the labels that each got.

#99 Implement EOT font building
  package-lock.json
  package.json
  scripts/build.js
  scripts/templates/base.css
Labels: enhancement

#100 Perform sanity check before automated releases
  .github/workflows/auto-release.yml
Labels: meta

#101 Implement OTF font building
  package-lock.json
  package.json
  scripts/build.js
  scripts/templates/base.css
Labels: enhancement

#102 Add composer.json to publish to Packagist
  README.md
  composer.json
Labels: docs, meta
